### ISSUE TITLE
Mission: Level1_HTML/CSS All Stage

### ISSUE THREAD

**Issue by ryehel7** [INCubiesIndonesia/Mission-Quest#4]
Name : ryehel7 mengambil Mission[ Level1](https://github.com/INCubiesIndonesia/Mission-Quest/tree/master/Mission/TrainingCamp/Level1_HTML-CSS)

Estimate : 1 week.

**Comment by WeirdWired** [comment]
Got it !

**Comment by WeirdWired** [comment]
bantu mengerjakan mission 2 PHP

**Comment by ryehel7** [comment]
Jgn formal donk 😥

**Comment by ryehel7** [comment]
Tugas pak CR nih udh aku bikinin
tinggal di edit

2018-03-12 17:50 GMT+07:00 HELEN FEBRI <
helen.febri15063@student.unsika.ac.id>:

> Jgn formal donk 😥
>

**Comment by ryehel7** [comment]
pake pengertian nya di tambah'


2018-03-12 21:59 GMT+07:00 HELEN FEBRI <
helen.febri15063@student.unsika.ac.id>:

> Tugas pak CR nih udh aku bikinin
> tinggal di edit
>
> 2018-03-12 17:50 GMT+07:00 HELEN FEBRI <helen.febri15063@student.
> unsika.ac.id>:
>
>> Jgn formal donk 😥
>>
