### ISSUE TITLE
Mission: Level1_HTML/CSS All Stage

### ISSUE THREAD

**Issue by MochJaf** [INCubiesIndonesia/Mission-Quest#5]
nama : MochJaf ambil misi [level 1](https://github.com/INCubiesIndonesia/Mission-Quest/tree/master/Mission/TrainingCamp/Level1_HTML-CSS)
waktu : 1 minggu

**Comment by WeirdWired** [comment]
Okay !

**Comment by WeirdWired** [comment]
push di mission 1 bukan di luar
