### ISSUE TITLE
Mission: #HTML-CSS#level1#All stage

### ISSUE THREAD

**Issue by descanears** [INCubiesIndonesia/Mission-Quest#6]
name : descanears mengambil mission [Level 1](https://github.com/INCubiesIndonesia/Mission-Quest/tree/master/Mission/TrainingCamp/Level1_HTML-CSS)

estimate : 1 minggu

**Comment by WeirdWired** [comment]
Okay !

**Comment by WeirdWired** [comment]
selesai,
