### ISSUE TITLE
html/css level 1 all stage(EXPIRED)

### ISSUE THREAD

**Issue by erlydwiariyanti** [INCubiesIndonesia/Mission-Quest#7]
Nama : erlydwiariyanti mengambil
[misi 1](https://github.com/INCubiesIndonesia/Mission-Quest/tree/master/Mission/TrainingCamp/Level1_HTML-CSS) 

estimasi 1 minggu

**Comment by WeirdWired** [comment]
Sip!

**Comment by WeirdWired** [comment]
Mission sudah expired di tunggu hasilnya

**Comment by WeirdWired** [comment]
expired
