### ISSUE TITLE
Mission : #HTML-CSS#Level1#All Stage

### ISSUE THREAD

**Issue by hilmykun** [INCubiesIndonesia/Mission-Quest#8]
Nama : Hilmy Kun Mengambil Mission [Level 1](https://github.com/INCubiesIndonesia/Mission-Quest/tree/master/Mission/TrainingCamp/Level1_HTML-CSS)

Estimate : 1 Minggu 

ty

**Comment by WeirdWired** [comment]
Kerjakan.

**Comment by WeirdWired** [comment]
Mission sudah expired di tunggu hasilnya

**Comment by WeirdWired** [comment]
ok
